version: "3.9"

services:
  db:
    image: mysql:5.5
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      USER: root
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    container_name: django_container
    build: .
    command: python2 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

